### ISSUE TITLE
Symbol not found in dataflow.cpython-39-darwin.so

### ISSUE THREAD

**Issue by DarcyIW** [datatheorem/strongarm#1]
Hi,
I have installed strongarm-ios using `pip install strongarm-ios`
but I got the wrong with
```from strongarm_dataflow.dataflow import get_register_contents_at_instruction_fast
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/strongarm_dataflow/dataflow.cpython-39-darwin.so, 2): Symbol not found: _cs_disasm
  Referenced from: /opt/homebrew/lib/python3.9/site-packages/strongarm_dataflow/dataflow.cpython-39-darwin.so
  Expected in: flat namespace
 in /opt/homebrew/lib/python3.9/site-packages/strongarm_dataflow/dataflow.cpython-39-darwin.so
```
I am using Mac OSX 11.4 with python3.9
install with strongarm_dataflow-2.1.5-cp39-cp39-macosx_11_0_arm64.whl 
Thanks.

**Comment by codyd51** [comment]
Hi! From the error message, it looks as though Capstone hasn't been installed. Could you verify if this is the case, and install it with `brew install capstone` if necessary? Thanks!

**Comment by dlevi309** [comment]
I'm also missing the `_cs_disasm` symbol, and I've confirmed capstone is installed as well

**Comment by EthanArbuckle** [comment]
@codyd51 The x86 dataflow wheel contains `.dylib/libcapstone.4.dylib` which is dynamically linked by `dataflow.cpython-39-darwin.so` (via load command). The arm64 wheel does not contain a capstone dylib and the dataflow module has no linkage to capstone afaict.

@dlevi309 I assume you're on arm64 as well? As a short-term solution, you could try one of the following hacks:

1. use optool (or a similar tool) to add a `LC_LOAD_DYLIB` command to `dataflow.cpython-39-darwin.so` that points to wherever libcapstone.dylib is on your system.

2. Create an intermediary binary that statically links libcapstone.a and dynamically links (via `dlopen`) `dataflow.cpython-39-darwin.so` (but renamed to something else), then name the intermediary binary `dataflow.cpython-39-darwin.so` and stick it wherever the original was

**Comment by dlevi309** [comment]
@EthanArbuckle Yes, I am on an M1, and thanks man! I appreciate the quick response, and will definitely do this 👍

**Comment by EthanArbuckle** [comment]
@dlevi309 please report back if it works, im curious. We'll have fixed wheels published to pypy soon

**Comment by codyd51** [comment]
Following up on this, we've got fixed wheels published to PyPI now. @dlevi309 could you please try reinstalling strongarm? I think you should use an invocation like the following to ensure all the dependencies are reinstalled afresh: 
`pip install --force-reinstall --no-cache-dir strongarm-ios`

**Comment by EthanArbuckle** [comment]
@dlevi309 @79cac has your issue been resolved?

**Comment by dlevi309** [comment]
> @dlevi309 @79cac has your issue been resolved?

Hey, I'm sorry I never got back to either of you guys, I've been really busy, but I'm glad to report that I was able to get this working through unpacking the dataflow.so file and crafting a couple of changes with `vtool`. Although I played with a bunch of different stuff so I'm not entirely sure what led to it's success, but thank you! I'm all good over here

**Comment by DarcyIW** [comment]
> @dlevi309 @79cac has your issue been resolved?

Hi,I'm sorry for taking so long to reply to you. I like this project and have learned a lot in it. In fact I have been using ubuntu well. I tried `pip install --force-reinstall --no-cache-dir strongarm-ios` and now it can work well in Mac M1.
Thanks!

**Comment by codyd51** [comment]
Glad to hear it! I'll close this issue out.
