### ISSUE TITLE
Do you guys think you could add an arm64 build to future releases of `strongarm-dataflow`? 

### ISSUE THREAD

**Issue by dlevi309** [datatheorem/strongarm#4]
it’s difficult to keep up with the latest builds as x86_64 is the only arch consistently uploaded

**Comment by codyd51** [comment]
Hi Daniel, thanks for reaching out. I don't have a personal M1 handy, but I'll see what I can do to incorporate arm64 builds into future releases of `strongarm-dataflow`. I'll also ping in this issue once I've gotten an arm64 build for the current release uploaded; should happen tomorrow. Cool to hear that you're keeping up with recent releases!

**Comment by dlevi309** [comment]
Of course, and thank you! I also incorporate the arm64 builds for running on iOS with my jailbroken device, here's a build for that if you have any jailbroken devices handy: 
[strongarm-for-ios.tar.gz](https://github.com/datatheorem/strongarm/files/9814602/strongarm-for-ios.tar.gz)

**Comment by codyd51** [comment]
No worries at all =) I uploaded arm64 wheels for `strongarm-dataflow @ 3.0.0` on Wednesday, and have incorporated this step into the process for future releases. 

That's really cool, thanks for sharing. I would be curious to hear what you're using SA for -- please feel free to reach out to me publicly or privately. I will close out this issue for now.
