### ISSUE TITLE
[Question] What does "Failed to find a corresponding ObjC class for ref ~ " mean?

### ISSUE THREAD

**Issue by yyokii** [datatheorem/strongarm#5]
When the following code is executed
I get the output 
`Failed to find a corresponding ObjC class for ref 0x10000000050ff8 from ObjcCategory(<Base class of Service category @ 0x100050210 will be populated later> (Service))`

```py
from pathlib import Path
from strongarm.macho import MachoParser, MachoBinary, MachoAnalyzer

macho_parser = MachoParser(Path("~/Desktop/MyApp.app/MyApp"))
binary: MachoBinary = macho_parser.get_arm64_slice()

analyzer = MachoAnalyzer.get_analyzer(binary)
for call in analyzer.objc_calls_to(["_OBJC_CLASS_$_UIAlertView"], ["init"], requires_class_and_sel_found=True):
    offset_within_func = call.caller_addr - call.caller_func_start_address
    print(f'Found call to -[UIAlertView init] at {call.caller_func_start_address} + {offset_within_func}')

```

What does this fail indicate?
Is there something wrong with my code? Or is it something I can ignore?

Thank you!

**Comment by codyd51** [comment]
Hello!

An an end-user you can feel free to ignore this log line, and it does not indicate anything wrong with your code. 

More technically, I can't give a full answer without access to the binary in question , but can give some context with what I've encountered before. 

Back in 2020 I added logic to strongarm to link ObjC category base-classes and ObjC class super-classes, after which I encountered this log:

`ERROR:root:Failed to find a corresponding ObjC class for ref 0x0 from ObjcClass(_TtCs12_SwiftObject : None)`

What’s happening here is that there’s an Objective-C class, `_TtCs12_SwiftObject` , that has the unbound null pointer as its superclass entry.

After a quick look online it’s a [special class hard-coded](https://github.com/apple/swift/blob/master/stdlib/public/runtime/SwiftObject.h#L36) into the Swift rt for ObjC interop. It serves as the root class for any Swift class annotated with @objc.

Please feel free to let me know if you have any other questions!

**Comment by codyd51** [comment]
I just noticed that the classref in your log-line is a non-NULL pointer. There may be some flag bits in the pointer that we're not parsing correctly, but that's just an off-the-cuff guess.

**Comment by yyokii** [comment]
@codyd51 
Thanks for your reply, very helpful!
