### ISSUE TITLE
Can't install strongarm-dataflow

### ISSUE THREAD

**Issue by tien0246** [datatheorem/strongarm#8]
Hello, i tried install strongarm-dataflow but got error
ERROR: Could not find a version that satisfies the requirement strongarm-dataflow (from versions: none)
ERROR: No matching distribution found for strongarm-dataflow
Could you help me?
I using win 10 with python 3.7

**Comment by codyd51** [comment]
Hi! `strongarm-dataflow` is a binary-only wheel, meaning that I need to specifically publish releases for each `(operating system, Python version)` pair. 

I'll give a go to building and publishing wheels for Windows / Python 3.7, and will follow-up in this thread once done. Thanks for the heads up!

**Comment by tien0246** [comment]
So, What version python can download?

**Comment by codyd51** [comment]
The available wheels for the latest release can be browsed [here](https://pypi.org/project/strongarm-dataflow/#files). As you can see, `strongarm-dataflow` currently has prebuilt wheels for Linux and several macOS versions across Python 3.7 through 3.11.

**Comment by tien0246** [comment]
Thank you. Looking forward to the Windows version.

**Comment by waruhachi** [comment]
Can you also upload the version for macOS ARM64 and Python 3.13.1?
